# Based partially on Alyxia's work, thanks so much!

name: Release
on:
  push:
    tags:
      - v*

env:
  FORCE_COLOR: true

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y pkg-config libsdl2-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libglx-dev libgl1-mesa-dev libxxf86vm-dev libglfw3-dev libwayland-dev libwayland-egl1 libegl-dev libxkbcommon-dev wayland-protocols extra-cmake-modules

      - name: Install Go dependencies
        run: go get -v

      - name: Recreate vendor and apply Wayland patches
        run: |
          go mod vendor
          git apply patches/wayland.patch

      - name: Build GUI (X11)
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v -tags static -ldflags "-s
          -w -X 'bhoplotl/buildinfo.InstallerGitHash=$(git rev-parse --short
          HEAD)' -X 'bhoplotl/buildinfo.InstallerTag=${{ github.ref_name }}'" -o
          Bhoplotl-x11

      - name: Build GUI (Wayland)
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v -tags "static wayland"
          -ldflags "-s -w -X 'bhoplotl/buildinfo.InstallerGitHash=$(git
          rev-parse --short HEAD)' -X 'bhoplotl/buildinfo.InstallerTag=${{
          github.ref_name }}'" -o Bhoplotl-wayland

      - name: Build GUI (Combined)
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v -tags "static combined"
          -ldflags "-s -w -X 'bhoplotl/buildinfo.InstallerGitHash=$(git
          rev-parse --short HEAD)' -X 'bhoplotl/buildinfo.InstallerTag=${{
          github.ref_name }}'" -o Bhoplotl

      - name: Build CLI
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v -tags "cli" -ldflags "-s
          -w -X 'bhoplotl/buildinfo.InstallerGitHash=$(git rev-parse --short
          HEAD)' -X 'bhoplotl/buildinfo.InstallerTag=${{ github.ref_name }}'" -o
          BhoplotlCli-linux

      - name: Update executable
        run: |
          chmod +x Bhoplotl*

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Bhoplotl-linux
          path: |
            Bhoplotl-x11
            Bhoplotl-wayland
            Bhoplotl
            BhoplotlCli-linux



  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"

      - uses: actions/cache@v5
        with:
          path: |
            ~\AppData\Local\go-build
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit

      - name: Install Windows dependencies
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm git mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2

      - name: Install Go dependencies
        shell: msys2 {0}
        run: |
          go get -v
          go install github.com/tc-hib/go-winres@latest

      - name: Build GUI
        shell: msys2 {0}
        run: |
          go-winres make --product-version "git-tag"
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -v -tags "static gui" -ldflags "-s -w -H=windowsgui -extldflags=-static -X 'bhoplotl/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'bhoplotl/buildinfo.InstallerTag=${{ github.ref_name }}'" -o Bhoplotl.exe

      - name: Build CLI
        shell: msys2 {0}
        run: |
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -v -tags "cli" -ldflags "-s -w -X 'bhoplotl/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'bhoplotl/buildinfo.InstallerTag=${{ github.ref_name }}'" -o BhoplotlCli.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Bhoplotl-windows
          path: |
            Bhoplotl.exe
            BhoplotlCli.exe

  release:
    runs-on: ubuntu-latest
    needs: [ build-linux, build-windows ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: "Download Linux Artifacts"
        uses: actions/download-artifact@v8
        with:
          name: Bhoplotl-linux
          path: linux

      - name: "Download Windows Artifacts"
        uses: actions/download-artifact@v8
        with:
          name: Bhoplotl-windows
          path: windows

      - name: Delete existing release
        run: gh release delete "${{ github.ref_name }}" --yes || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          make_latest: ${{ !contains(github.ref_name, '-') }}
          prerelease: ${{ contains(github.ref_name, '-') }}
          draft: false
          body: |
            This is release ${{ github.ref_name }} of Bhoplotl.
          files: |
            linux/Bhoplotl-x11
            linux/Bhoplotl-wayland
            linux/Bhoplotl
            linux/BhoplotlCli-linux
            windows/Bhoplotl*.exe
